import React, { useState } from "react";
import type { NextPage } from "next";
import styled from "styled-components";
import media from "../styles/media";
import { SharedTitleStyle } from "../styles/shared";
import Image from "next/image";
import Data from "../../data.json";
import Head from "next/head";

const CrewEl = styled.div`
  background-image: url(/images/crew/background-crew-mobile.jpg);
  background-size: cover;
  min-height: 100vh;

  ${media.tablet} {
    background-image: url(/images/crew/background-crew-tablet.jpg);
    height: 100vh;
    overflow: hidden;
  }

  ${media.laptop} {
    background-image: url(/images/crew/background-crew-desktop.jpg);
  }
`;

const Wrapper = styled.div`
  padding: 8.8rem 4.6rem;

  ${media.tablet} {
    padding-top: 13.6rem;
  }

  ${media.laptop} {
    position: relative;
    padding-top: 21.2rem;
    height: 100vh;
    width: 128rem;
    margin-inline: auto;
  }
`;

const Content = styled.div`
  margin-top: 3.2rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 3.2rem;

  ${media.tablet} {
    order: 1;
  }

  ${media.laptop} {
    flex-direction: row;
  }
`;

const MainContent = styled.div`
  text-align: center;

  ${media.tablet} {
    display: flex;
    flex-direction: column;
  }

  ${media.laptop} {
    text-align: start;
  }
`;

const DotsWrapper = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 1.6rem;
  margin-bottom: 3.6rem;

  ${media.tablet} {
    order: 5;
    margin-bottom: 0rem;
    margin-top: 3.6rem;
  }

  ${media.laptop} {
    justify-content: flex-start;
    margin-top: 12rem;
  }
`;

const Dot = styled.div`
  width: 1rem;
  height: 1rem;
  border-radius: 50%;
  background-color: white;
  opacity: 17.44%;
  transition: all 0.3s;
  cursor: pointer;

  &.active {
    opacity: 100%;
  }

  ${media.laptop} {
    width: 1.5rem;
    height: 1.5rem;
  }
`;

const ImageWrapper = styled.div`
  position: relative;
  /* width: 32.7rem; */
  width: 100%;

  height: 30rem;
  border-bottom: 1px solid gray;
  ${media.tablet} {
    order: 2;
    border-bottom: none;
    height: 50rem;
  }

  ${media.laptop} {
    display: none;
  }
`;

const DesktopImageWrapper = styled.div`
  position: absolute;
  display: none;
  right: 0;
  bottom: 0;

  ${media.laptop} {
    display: block;
    height: 63.2rem;
    width: 56.8rem;
  }
`;

const CrewPost = styled.h4`
  opacity: 0.5;
  margin-bottom: 1rem;

  ${media.tablet} {
  }
`;

const BioStyle = styled.p`
  margin-top: 2rem;

  ${media.tablet} {
    width: 44.4rem;
  }
`;

const Crew: NextPage = () => {
  const crewArr = Data.crew;

  const [currentIndex, setCurrentIndex] = useState(0);
  return (
    <CrewEl>
      <Head>
        <title> Crew | Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <DesktopImageWrapper>
          <Image
            alt="earth"
            src={crewArr[currentIndex].images.webp}
            layout="fill"
            objectFit="contain"
          />
        </DesktopImageWrapper>
        <SharedTitleStyle>
          <span>02</span> Meet your crew
        </SharedTitleStyle>
        <Content>
          <ImageWrapper>
            <Image
              alt="earth"
              src={crewArr[currentIndex].images.webp}
              layout="fill"
              objectFit="contain"
            />
          </ImageWrapper>
          <MainContent>
            <DotsWrapper>
              <Dot
                className={currentIndex === 0 ? "active" : ""}
                onClick={() => setCurrentIndex(0)}
              />
              <Dot
                className={currentIndex === 1 ? "active" : ""}
                onClick={() => setCurrentIndex(1)}
              />
              <Dot
                className={currentIndex === 2 ? "active" : ""}
                onClick={() => setCurrentIndex(2)}
              />
              <Dot
                className={currentIndex === 3 ? "active" : ""}
                onClick={() => setCurrentIndex(3)}
              />
            </DotsWrapper>

            <CrewPost>{crewArr[currentIndex].role}</CrewPost>
            <h3>{crewArr[currentIndex].name}</h3>
            <BioStyle>{crewArr[currentIndex].bio}</BioStyle>
          </MainContent>
        </Content>
      </Wrapper>
    </CrewEl>
  );
};

export default Crew;
