import React, { useState } from "react";
import type { NextPage } from "next";
import styled from "styled-components";
import media from "../styles/media";
import { SharedTitleStyle, SubHeading1, SubHeading2 } from "../styles/shared";
import Image from "next/image";
import Data from "../../data.json";
import Head from "next/head";

const DestinationEl = styled.div`
  background-image: url(/images/destination/background-destination-mobile.jpg);
  background-size: cover;
  min-height: 100vh;

  ${media.tablet} {
    background-image: url(/images/destination/background-destination-tablet.jpg);
  }

  ${media.laptop} {
    background-image: url(/images/destination/background-destination-desktop.jpg);
    height: 100vh;
    overflow: hidden;
  }
`;

const Wrapper = styled.div`
  text-align: center;
  padding: 8.8rem 4.6rem;

  ${media.tablet} {
    text-align: start;

    padding-top: 13.6rem;
  }

  ${media.laptop} {
    padding-top: 21.2rem;
    width: 128rem;
    margin-inline: auto;
  }
`;

const ImageWrapper = styled.div`
  position: relative;
  margin-block: 3.2rem 2.6rem;
  height: 17rem;
  width: 17rem;

  ${media.tablet} {
    margin-block: 6rem 5.4rem;
    height: 30rem;
    width: 30rem;
  }

  ${media.laptop} {
    margin-block: 0;
    height: 44.5rem;
    width: 44.5rem;
  }
`;

const Content = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;

  ${media.laptop} {
    flex-direction: row;
    align-items: center;
    text-align: start;
    justify-content: center;
    gap: 15rem;
    margin-top: 4rem;

    .main-content {
      width: 40%;
    }
  }
`;

const Menu = styled.ul`
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 2.6rem;

  ${media.laptop} {
    justify-content: flex-start;
  }
`;

const MenuItem = styled.li`
  position: relative;
  font-family: var(--font-primary-condensed);
  font-size: 1.4rem;
  color: var(--col-text);
  text-transform: uppercase;
  letter-spacing: 2.36px;
  cursor: pointer;
  margin-bottom: 3.2rem;

  &.active {
    color: var(--col-light);
  }

  &::after {
    content: "";
    display: inline-block;
    position: absolute;
    bottom: -5px;
    left: 0;
    width: 100%;
    height: 2px;
    transform: scale(0);
    transition: all 0.7s;
  }

  &:hover::after {
    transform: scale(100%);
    background-color: var(--col-text);
  }

  &.active::after {
    transform: scale(100%);
    background-color: var(--col-light);
  }
`;

const Text = styled.p`
  ${media.tablet} {
    padding-inline: 6rem;
  }

  ${media.laptop} {
    padding-inline: 0 12rem;
  }
`;

const DetailWrapper = styled.div`
  display: flex;
  flex-direction: column;
  gap: 3.2rem;
  margin-top: 3.2rem;
  padding: 3.2rem;
  border-top: 1px solid #383b4b;
  align-self: stretch;

  ${media.tablet} {
    flex-direction: row;
    justify-content: space-around;
    margin-top: 6rem;
  }

  ${media.laptop} {
    justify-content: flex-start;
    gap: 8rem;
    padding-left: 0;
    margin-top: 5.4rem;
  }
`;

const Detail = styled.div`
  display: flex;
  flex-direction: column;
  gap: 1.2rem;
`;

const Destination: NextPage = () => {
  const destinationsArr = Data.destinations;

  const [currentIndex, setCurrentIndex] = useState(0);

  return (
    <DestinationEl>
      <Head>
        <title> Destination | Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <SharedTitleStyle style={{ alignSelf: "flex-start" }}>
          <span>01</span> Pick your destination
        </SharedTitleStyle>

        <Content>
          <ImageWrapper>
            <Image
              alt="earth"
              src={destinationsArr[currentIndex].images.webp}
              layout="fill"
              objectFit="cover"
            />
          </ImageWrapper>
          <div className="main-content">
            <Menu>
              <MenuItem
                className={currentIndex === 0 ? "active" : ""}
                onClick={() => setCurrentIndex(0)}
              >
                Moon
              </MenuItem>
              <MenuItem
                className={currentIndex === 1 ? "active" : ""}
                onClick={() => setCurrentIndex(1)}
              >
                Mars
              </MenuItem>
              <MenuItem
                className={currentIndex === 2 ? "active" : ""}
                onClick={() => setCurrentIndex(2)}
              >
                Europa
              </MenuItem>
              <MenuItem
                className={currentIndex === 3 ? "active" : ""}
                onClick={() => setCurrentIndex(3)}
              >
                Titan
              </MenuItem>
            </Menu>

            <h2>{destinationsArr[currentIndex].name}</h2>

            <Text>{destinationsArr[currentIndex].description}</Text>

            <DetailWrapper>
              <Detail>
                <SubHeading2>Avg. distance</SubHeading2>
                <SubHeading1>
                  {destinationsArr[currentIndex].distance}
                </SubHeading1>
              </Detail>

              <Detail>
                <SubHeading2>Est. travel time</SubHeading2>
                <SubHeading1>
                  {destinationsArr[currentIndex].travel}
                </SubHeading1>
              </Detail>
            </DetailWrapper>
          </div>
        </Content>
      </Wrapper>
    </DestinationEl>
  );
};

export default Destination;
