import React, { useState } from "react";
import type { NextPage } from "next";
import styled from "styled-components";
import media from "../styles/media";
import { NavText, SharedTitleStyle } from "../styles/shared";
import Image from "next/image";
import Data from "../../data.json";
import Head from "next/head";

const TechnologyEl = styled.div`
  background-image: url(/images/technology/background-technology-mobile.jpg);
  background-size: cover;
  min-height: 100vh;

  ${media.tablet} {
    background-image: url(/images/technology/background-technology-tablet.jpg);
  }

  ${media.laptop} {
    background-image: url(/images/technology/background-technology-desktop.jpg);
  }
`;

const Wrapper = styled.div`
  padding-top: 8.8rem;

  ${media.tablet} {
    padding-top: 13rem;
    padding-bottom: 8rem;
  }

  ${media.laptop} {
    position: relative;
    padding-top: 21.2rem;
    width: 128rem;
    margin-inline: auto;
    height: 100vh;
  }
`;

const Content = styled.div`
  margin-top: 3.2rem;

  ${media.tablet} {
    margin-top: 5.6rem;
  }

  ${media.laptop} {
    margin-top: 8.6rem;
  }
`;

const ImageWrapper = styled.div`
  position: relative;
  width: 100%;
  height: 18rem;

  ${media.tablet} {
    height: 31rem;
  }

  ${media.laptop} {
    display: none;
  }
`;

const ButtonWrapper = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 1.6rem;

  ${media.laptop} {
    flex-direction: column;
    gap: 3.2rem;
  }
`;

const CircleButton = styled.button`
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid var(--col-darkgray);
  width: 4rem;
  height: 4rem;
  border-radius: 50%;
  color: var(--col-light);
  background-color: transparent;
  transition: all 0.5s;
  cursor: pointer;

  &.active {
    background-color: var(--col-light);
    color: var(--col-dark);
  }

  ${media.tablet} {
    width: 6rem;
    height: 6rem;
    font-size: 1.6rem;
  }

  ${media.laptop} {
    width: 8rem;
    height: 8rem;
    font-size: 1.8rem;
  }
`;

const MainContent = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 3.2rem;

  .detail {
    margin-top: 3.6rem;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    gap: 1rem;
    padding-inline: 4rem;
  }

  ${media.laptop} {
    flex-direction: row;
    margin-top: 0;
    gap: 4.4rem;

    .detail {
      margin-top: 0;

      align-items: flex-start;
      text-align: start;
      width: 600px;
    }
  }
`;

const DesktopImageWrapper = styled.div`
  position: absolute;
  display: none;
  right: 0;
  bottom: 10%;

  ${media.laptop} {
    display: block;
    height: 60rem;
    width: 50.8rem;
  }
`;

const Description = styled.p`
  margin-top: 1.8rem;
`;

const Technology: NextPage = () => {
  const technologyArr = Data.technology;

  const [currentIndex, setCurrentIndex] = useState(0);
  return (
    <TechnologyEl>
      <Head>
        <title> Technology | Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <DesktopImageWrapper>
          <Image
            alt="earth"
            src={technologyArr[currentIndex].images.portrait}
            layout="fill"
            objectFit="contain"
          />
        </DesktopImageWrapper>
        <SharedTitleStyle style={{ paddingInline: "4rem" }}>
          <span>03</span> Space launch 101
        </SharedTitleStyle>
        <Content>
          <ImageWrapper>
            <Image
              alt="earth"
              src={technologyArr[currentIndex].images.landscape}
              layout="fill"
              objectFit="cover"
            />
          </ImageWrapper>
          <MainContent>
            <ButtonWrapper>
              <CircleButton
                className={currentIndex === 0 ? "active" : ""}
                onClick={() => setCurrentIndex(0)}
              >
                1
              </CircleButton>
              <CircleButton
                className={currentIndex === 1 ? "active" : ""}
                onClick={() => setCurrentIndex(1)}
              >
                2
              </CircleButton>
              <CircleButton
                className={currentIndex === 2 ? "active" : ""}
                onClick={() => setCurrentIndex(2)}
              >
                3
              </CircleButton>
            </ButtonWrapper>

            <div className="detail">
              <NavText>The terminology...</NavText>
              <h3>{technologyArr[currentIndex].name}</h3>
              <Description>
                {technologyArr[currentIndex].description}
              </Description>
            </div>
          </MainContent>
        </Content>
      </Wrapper>
    </TechnologyEl>
  );
};

export default Technology;
